### PR TITLE
Ctrl+Z to undo last abbreviation.

### PR DESCRIPTION
**Pull request by sohan5005**
Useful if you want to keep words like "windows" :p

### CODE REVIEW

**Comment by hasinhayder** [comment]
Excellent work! Thanks a lot. However, there is a corner case

Say there are two textarea, and textExpander has been initiated with both, like this 

```javascript
textExpander([document.querySelector("#ta1"), document.querySelector("#ta2")], dictionary);
```

Then if I edit something in the first textarea, and then press ctrl+z in the second textarea, it will behave unexpectedly :)

Please fix this corner case and I will be so so happy to merge your pull request. Again, thanks a lot for the PR :) (y) Keep it up

**Comment by sohan5005** [comment]
Ok fixed now, works with any number of textarea!

**Comment by hasinhayder** [comment]
Did you check with Firefox and Safari?

**Comment by sohan5005** [comment]
Working so far on all major browsers. (Didn't check with internet explorer or edge)

**Comment by hasinhayder** [comment]
Thanks, merged

**Comment by sohan5005** [comment]
You're welcome! 💯

**Pull request merged**
